components:
#  #Example of Another Users/Account/Card... microservice instance config
#  - componentName: "Users-Component-02" # <- Change it.
#    instanceEurekaName: "Users-Component" # <- Don't Change it if it's the same type of component.
#    componentAddress: "localhost" # <- Change it.
#    componentPort: "8102" # <- Change it.
#    componentId: "a4ad33d9-382d-4cd4-9ce9-c7b941c14912" # <- Change it.
#    componentSecret: "UsersServicePassword" # <- Change it.
#################################################################################################
#  #Example of Another AppRegistry microservice
#  - componentName: "AppRegistry-Component-02" <- Change it.
#    instanceEurekaName: "AppRegistry-Component" <- Don't Change it if it's the same type of component.
#    componentAddress: "localhost" <- Change it.
#    componentPort: "8602" <- Change it.
#    componentId: "7de9eedd-8b4d-44b8-ab5a-155cffee465b" <- Change it.
#    componentSecret: "AppRegistryPassword" <- Change it.
 #Users microservice
  - componentName: "Users-Component-01"
    instanceEurekaName: "Users-Component"
    componentAddress: "localhost"
    componentPort: "8101"
    componentId: "a4ad33d9-382d-4cd4-9ce9-c7b941c14912"
    componentSecret: "UsersServicePassword"
 #Account microservice
  - componentName: "Account-Component-01"
    instanceEurekaName: "Account-Component"
    componentAddress: "localhost"
    componentPort: "8201"
    componentId: "c5acff7c-77f2-4026-b56e-2612ae7483d2"
    componentSecret: "AccountServicePassword"
  #Card microservice
  - componentName: "Card-Component-01"
    instanceEurekaName: "Card-Component"
    componentAddress: "localhost"
    componentPort: "8301"
    componentId: "1d8c6259-a859-4e13-88e6-49668a1e39c6"
    componentSecret: "CardServicePassword"
  #Payment microservice
  - componentName: "Payment-Component-01"
    instanceEurekaName: "Payment-Component"
    componentAddress: "localhost"
    componentPort: "8401"
    componentId: "1d8c6259-a859-4e13-88e6-49668a1e39c6"
    componentSecret: "PaymentServicePassword"
  #Security microservice
  - componentName: "Security-Component-01"
    instanceEurekaName: "Security-Component"
    componentAddress: "localhost"
    componentPort: "8501"
    componentId: "1414fdb6-dbbd-4e44-8db8-618850391e18"
    componentSecret: "SecurityServicePassword"
  #Eureka-Server microservice
  - componentName: "EurekaServer-Component-01"
    componentAddress: "localhost"
    componentPort: "8701"
    componentId: "0d9ac6d0-c62d-487f-9575-9b2b48837123"
    componentSecret: "EurekaServerPassword"