components:
  #  #Example of Another Users/Account/Card... microservice instance config
  #  - componentName: "Users-Component-02" # <- Change it.
  #    instanceEurekaName: "USERS-COMPONENTS" # <- Don't Change it if it's the same type of component.
  #    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
  #    componentAddress: "localhost" # <- Change it.
  #    componentPort: "8102" # <- Change it.
  #    componentId: "44f7da34-0adf-4efd-baae-43aaa9c8b5a6" # <- Change it.
  #    componentSecret: "UsersServicePassword" # <- Change it.
  #API-Gateway microservice
  - componentName: "ApiGateway-Component-01"
    instanceEurekaName: "APIGATEWAY-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8088"
    componentId: "5bd9e5cc-96d2-4743-b0f9-c71966c4158f"
    componentSecret: "ApiGatewayPassword"
  #Users microservice
  - componentName: "Users-Component-01"
    instanceEurekaName: "USERS-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8101"
    componentId: "a4ad33d9-382d-4cd4-9ce9-c7b941c14912"
    componentSecret: "UsersServicePassword"
  #Account microservice
  - componentName: "Account-Component-01"
    instanceEurekaName: "ACCOUNT-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8201"
    componentId: "c5acff7c-77f2-4026-b56e-2612ae7483d2"
    componentSecret: "AccountServicePassword"
  #Card microservice
  - componentName: "Card-Component-01"
    instanceEurekaName: "CARD-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8301"
    componentId: "1d8c6259-a859-4e13-88e6-49668a1e39c6"
    componentSecret: "CardServicePassword"
  #Payment microservice
  - componentName: "Payment-Component-01"
    instanceEurekaName: "PAYMENT-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8401"
    componentId: "cb9b8187-a5cc-408a-801c-ad991747dab3"
    componentSecret: "PaymentServicePassword"
  #Security microservice
  - componentName: "Security-Component-01"
    instanceEurekaName: "SECURITY-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8501"
    componentId: "1414fdb6-dbbd-4e44-8db8-618850391e18"
    componentSecret: "SecurityServicePassword"
  #AppRegistry microservice
  - componentName: "AppRegistry-Component-01"
    instanceEurekaName: "APPREGISTRY-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "localhost"
    componentPort: "8601"
    componentId: "7de9eedd-8b4d-44b8-ab5a-155cffee465b"
    componentSecret: "AppRegistryPassword"
  #Eureka-Server microservice
  - componentName: "EurekaServer-Component-01"
    instanceEurekaName: "EUREKA-COMPONENTS"
    kafkaBootstrapAddresses: "localhost:9092, localhost:9092"
    componentAddress: "127.0.0.1"
    componentPort: "8701"
    componentId: "0d9ac6d0-c62d-487f-9575-9b2b48837123"
    componentSecret: "EurekaServerPassword"